### PR TITLE
Fix iosxr_config bug while updating prefix-set,route-policy configura…

### PR DESCRIPTION
**Pull request by ashwini-mhatre**
##### SUMMARY

fixes https://github.com/ansible-collections/cisco.iosxr/issues/155

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

iosxr_config

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Review by rohitthakur2590 — APPROVED** [review]

**Pull request merged**
