### PR TITLE
add build ignore list to galaxy.yml

### PR DESCRIPTION
**Pull request by sean-m-sullivan**
##### SUMMARY
The following files have been causing alerts on customers security scans
RSA Private Key
collections/ansible_collections/cisco/ios/tests/integration/targets/ios_user/files/test_rsa
Generic High Entropy Secret
collections/ansible_collections/cisco/iosxr/plugins/modules/iosxr_user.py
RSA Private Key
collections/ansible_collections/cisco/iosxr/tests/integration/targets/iosxr_user/files/private

The solution should be that we don't distribute the test files in our galaxy build tarballs. They are fine in tests, just need to not distribute them. This PR achieves that.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
Test Files

### CODE REVIEW

**Comment by sean-m-sullivan** [comment]
I am not seeing how deeply rooted this is, we've sometimes run the tests out of the repo, after installing, rather then from the installed source, looking at options, and would appreciate any feedback

**Comment by ashwini-mhatre** [comment]
@sean-m-sullivan uts and sanity tests are failing. Could you please look into it?

**Comment by sean-m-sullivan** [comment]
I believe we've engaged this from the otherside as a customer request, I haven't had time, but it is how the underlying tests are done and will require a change to network tools first, I have been looking at how to do that without disrupting things.

**Comment by ashwini-mhatre** [comment]
working on another solution

**Comment by sean-m-sullivan** [comment]
Going to close this, was thinking I'd try things, but have run into other obligations

**Comment by ashwini-mhatre** [comment]
> Going to close this, was thinking I'd try things, but have run into other obligations

NP. I am fixing it

**Pull request closed without merging**
