### PR TITLE
Add support single_user_mode

### PR DESCRIPTION
**Pull request by NilashishC**
##### SUMMARY
- Targets https://github.com/ansible-collections/ansible.netcommon/issues/73
- Add support for `ansible_single_user_mode` option added in network_cli.
- Re-use device_info dictionary for every session.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
cliconf/iosxr.py
terminal/iosxr.py

### CODE REVIEW

**Comment by NilashishC** [comment]
recheck

**Comment by trishnaguha** [comment]
@ashwini-mhatre Please review the PR.

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
LGTM.

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Comment by NilashishC** [comment]
recheck

**Pull request merged**
