### PR TITLE
Remove tests/sanity/requirements.txt

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
https://github.com/ansible-collections/overview/issues/43

### CODE REVIEW

**Comment by ashwini-mhatre** [comment]
@Andersson007 Could you please add a changelog fragment with a trivial section so that CI passes?

**Comment by Andersson007** [comment]
@ashwini-mhatre thanks for the hint! will do

**Comment by Andersson007** [comment]
done
ready_for_review

**Review by ashwini-mhatre — APPROVED** [review]

**Comment by Andersson007** [comment]
@ashwini-mhatre could you also look at a similar PR https://github.com/ansible-collections/cisco.asa/pull/94 or tell me who I should mention there?

**Comment by Andersson007** [comment]
@ashwini-mhatre thanks for reviewing!

**Pull request merged**
