### PR TITLE
fix issue in prefix-lists facts code when prefix-lists facts are empty

### PR DESCRIPTION
**Pull request by ashwini-mhatre**
##### SUMMARY

fixes: https://github.com/ansible-collections/cisco.iosxr/issues/162

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by priyamsahoo** [comment]
LGTM!

**Review by rohitthakur2590 — APPROVED** [review]

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Pull request merged**
