### PR TITLE
[IOSXR]: interface description parsing fix

### PR DESCRIPTION
**Pull request by rohitthakur2590**
Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/620

##### SUMMARY

resolve: https://github.com/ansible-collections/cisco.iosxr/issues/64

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

 iosxr_interfaces
 iosxr_l2_interfaces
 iosxr_l3_interfaces
 iosxr_lacp_interfaces
 iosxr_lag_interfaces
 iosxr_lldp_interfaces

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by rohitthakur2590** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by rohitthakur2590** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Pull request merged**
