### PR TITLE
README: Add Communication section with Forum information

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Dear maintainers,
As a part of the [Consolidating Ansible discussion platforms initiative](https://forum.ansible.com/t/proposal-consolidating-ansible-discussion-platforms/6812), this PR adds the communication section template defined by the community to the README. Similar PRs are being raised across all included collections under the ansible-collection org for now.

- If you have your forum group and/or tags related to the collection, please update corresponding lines by suggesting changes to the PR.
- If the collection is not present on the Ansible forum yet, please check out the existing [tags](https://forum.ansible.com/tags) and [groups](https://forum.ansible.com/g) - use what suits your collection. If there is no appropritate tag and group yet, please [request one](https://forum.ansible.com/t/requesting-a-forum-group/503/17). Then update corresponding lines by suggesting changes to the PR.
- Presence in the forum will soon likely become a part of the Collection inclusion requirements.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME
README.md

### CODE REVIEW

**Comment by Andersson007** [comment]
i don't think the CI failures are related, so ready for review

**Comment by Andersson007** [comment]
i don't see the failures are related, ready for review

**Review by Ruchip16 — APPROVED** [review]
looks good to me!

**Comment by Andersson007** [comment]
@Ruchip16 thanks for merging, though i'm afraid you were a bit fast:)
The following points had to be addressed before merging:
```
  * [Posts tagged with 'your tag'](https://forum.ansible.com/tag/YOUR_TAG): subscribe to participate in collection-related conversations.
  * [Refer to your forum group here if exists](https://forum.ansible.com/g/): by joining the team you will automatically get subscribed to the posts tagged with [your group forum tag here](https://forum.ansible.com/tags).
 ```
Please update it in another PR.
If you need a forum tag for the collections, please see the issue description

**Comment by Ruchip16** [comment]
@Andersson007 here is the updated PR: https://github.com/ansible-collections/cisco.iosxr/pull/505/files
can you take a look at the PR once and apologies for the merge, i overlooked it, but corrected it instantly.

**Comment by Andersson007** [comment]
> @Andersson007 here is the updated PR: https://github.com/ansible-collections/cisco.iosxr/pull/505/files can you take a look at the PR once and apologies for the merge, i overlooked it, but corrected it instantly.

@Ruchip16 no worries, lgtm, approved, thanks!

**Pull request merged**
