### PR TITLE
fix intermittent failures in CI

### PR DESCRIPTION
**Pull request by ashwini-mhatre**
##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Review by rohitthakur2590 — APPROVED** [review]

**Comment by GomathiselviS** [comment]
recheck

**Pull request merged**
