### PR TITLE
DNM:reproduce retry_limit issue

### PR DESCRIPTION
**Pull request by ashwini-mhatre**
##### SUMMARY

Test if integration tests are running for iosxr.

https://github.com/ansible/ansible-zuul-jobs/pull/941

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by pabelanger** [comment]
can you please make sure to open these PRs against your fork, not under github.com/ansible-collections.

Thanks!

**Pull request closed without merging**
