### PR TITLE
DNM: Test image upgrade

### PR DESCRIPTION
**Pull request by GomathiselviS**
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>

Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/827

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by GomathiselviS** [comment]
cc @ashwini-mhatre

**Comment by GomathiselviS** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
iosxr upgrade is done

**Pull request closed without merging**
