### PR TITLE
Pylint and Python 2.6 sanity ignore updates

### PR DESCRIPTION
**Pull request by alisonlhart**
##### SUMMARY

This resolves Python 2.6 and Pylint errors showing in the Automation Hub import log for cisco.iosxr v3.2.0.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ansible-test sanity ignore file (ignore-2.12.txt)

##### ADDITIONAL INFORMATION

This is not a current requirement, but removing all ansible-test sanity errors is encouraged by the community. 
See this community-topics issue for reference: https://github.com/ansible-community/community-topics/issues/96

```
Running sanity test "compile" on Python 2.6 
ERROR: Found 2 compile issue(s) on python 2.6 which need to be resolved: 
ERROR: plugins/module_utils/network/iosxr/config/ntp_global/ntp_global.py:172:36: SyntaxError: i["name"]: i for i in tmp["access_group"]["vrfs"] 
ERROR: plugins/module_utils/network/iosxr/config/snmp_server/snmp_server.py:355:54: SyntaxError: x["context"] = {y: {"name": y} for y in x["context"]} 

ERROR: Found 2 pylint issue(s) which need to be resolved: 
ERROR: tests/sanity/ignore-2.12.txt:31:1: ansible-test: Ignoring 'arguments-renamed' on 'plugins/cliconf/iosxr.py' is unnecessary 
ERROR: tests/sanity/ignore-2.12.txt:32:1: ansible-test: Ignoring 'arguments-renamed' on 'plugins/netconf/iosxr.py' is unnecessary 
```

### CODE REVIEW

**Comment by KB-perByte** [comment]
recheck

**Comment by KB-perByte** [comment]
Hey @alisonlhart would you please rebase the PR, I can get it merged right after that,

**Comment by alisonlhart** [comment]
@KB-perByte Rebase is complete.

**Comment by KB-perByte** [comment]
Hey @alisonlhart I see some of the 2.12 sanity tests are failing considering the change that were made as of this PR.
I have a check PR based on main the tests are green without the changes https://github.com/ansible-collections/cisco.iosxr/pull/265 that is un-usual 
would you please have a look
Regards

**Comment by Ruchip16** [comment]
closing this as we dont support python 2.6 anymore.

**Pull request closed without merging**
