### PR TITLE
Fix issue in static_routes parsing

### PR DESCRIPTION
**Pull request by ashwini-mhatre**
##### SUMMARY

Fixes https://github.com/ansible-collections/cisco.iosxr/issues/152

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

iosxr_static_routes
##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
recheck

**Comment by ashwini-mhatre** [comment]
Recheck

**Review by NilashishC — APPROVED** [review]

**Comment by ashwini-mhatre** [comment]
recheck

**Pull request merged**
